Repository hzi-braunschweig/SORMAS-Docker, pull requests merged in 2021-07, with the labels that each got.

#246 Solution (2) for fixed postgres 10-alpine version
  postgres/Dockerfile
Labels: bug

#244 Adding file-backup functionality (HCSA-818)
  .env
  docker-compose-keycloak.yml
  docker-compose-s2s.yml
  docker-compose-sb-keycloak.yml
  docker-compose-sb.yml
  docker-compose.yml
  docker-compose_nginx.yml
  pg_dump/Dockerfile
  pg_dump/pg_dump
Labels: enhancement

#254 ADD data path in order to save state
  central/docker-compose.yml
Labels: bug, enhancement
